from .model import Model
from .util import date_fields, model_field

class Assignment(Model):
    _fields = (
        'id',
        'name',
        'description',
        *date_fields('created_at', 'updated_at', 'due_at', 'lock_at', 'unlock_at'),
        'has_overrides',
        'all_dates',
        'course_id',
        'html_url',
        'submissions_download_url',
        'assignment_group_id',
        'due_date_required',
        'allowed_extensions',
        'max_name_length',
        'turnitin_enabled', 'vericite_enabled', 'turnitin_settings',
        'grade_group_students_individually',
        'external_tool_tag_attributes',
        'peer_reviews', 'automatic_peer_reviews', 'peer_review_count',
        *date_fields('peer_reviews_assign_at'),
        'intra_group_peer_reviews',
        'group_category_id',
        'needs_grading_count',
        'needs_grading_count_by_section',
        'position',
        'post_to_sis',
        'integration_id',
        'points_possible',
        'submission_types',
        'has_submitted_submissions',
        'grading_type',
        'grading_standard_id',
        'published',
        'unpublishable',
        'only_visible_to_overrides',
        'locked_for_user', 'lock_info', 'lock_explanation',
        'quiz_id', 'anonymous_submissions',
        'discussion_topic',
        'freeze_on_copy', 'frozen', 'frozen_attributes',
        'submission',
        'use_rubric_for_grading', 'rubric_settings', 'rubric',
        'assignment_visibility',
        'overrides',
        'omit_from_final_grade',
        'hide_in_gradebook',
        'moderated_grading', 'grader_count', 'final_grader_id', 'grader_comments_visible_to_graders',
        'graders_anonymous_to_graders', 'grader_names_visible_to_final_grader', 'anonymous_grading',
        'allowed_attempts',
        'post_manually',
        'score_statistics',
        'can_submit',
        'ab_guid',
        'annotatable_attachment_id',
        'anonymize_students',
        'require_lockdown_browser',
        'important_dates',
        'muted',
        'anonymous_peer_reviews', 'anonymous_instructor_annotations',
        'graded_submissions_exist',
        'is_quiz_assignment',
        'in_closed_grading_period',
        'can_duplicate',
        'original_course_id', 'original_assignment_id', 'original_lti_resource_link_id',
        'original_assignment_name', 'original_quiz_id',
        'workflow_state'
    )
